# Generated by Django 2.2.7 on 2019-11-15 11:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_title', models.CharField(max_length=255)),
                ('summary', models.CharField(max_length=255)),
                ('describe', models.TextField()),
                ('price', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('category', models.CharField(choices=[('요리', '요리'), ('수공예', '수공예'), ('꽃', '꽃'), ('미술', '미술'), ('음악', '음악'), ('미용', '미용'), ('운동', '운동'), ('커피/차', '커피/차')], max_length=10)),
                ('current_number', models.IntegerField()),
                ('max_number', models.IntegerField()),
                ('img1', models.ImageField(blank=True, null=True, upload_to='')),
                ('img2', models.ImageField(blank=True, null=True, upload_to='')),
                ('img3', models.ImageField(blank=True, null=True, upload_to='')),
                ('img4', models.ImageField(blank=True, null=True, upload_to='')),
                ('img5', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(default=5)),
                ('content', models.TextField(blank=True, max_length=500)),
                ('review_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classregister.Class')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classregister.Class')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
