# Generated by Django 2.2.7 on 2019-11-15 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storeregister', '__first__'),
        ('classregister', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='store_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='storeregister.Store'),
            preserve_default=False,
        ),
    ]
