# Generated by Django 2.2.7 on 2019-11-16 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classregister', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='current_number',
            field=models.IntegerField(default=0),
        ),
    ]
