# Generated by Django 2.2.7 on 2019-11-16 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeregister', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='store/'),
        ),
    ]
