# Generated by Django 2.2.7 on 2019-11-22 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cardnews', '0002_auto_20191122_1302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='photo10',
        ),
        migrations.RemoveField(
            model_name='news',
            name='photo9',
        ),
    ]
